### PR TITLE
Convert Dockerfile to use Alpine

### PR DESCRIPTION
**Pull request by eta-ableton**
First step to closing https://github.com/AbletonAppDev/devtools/issues/1431.

ptal @AbletonDevTools/gotham-city, thanks!

### CODE REVIEW

**Comment by mst-ableton** [comment]
I'll follow Alain's lead and not lgtm my own code, but I would say that this PR should be renamed to something like "Convert jenkins_exporter Dockerfile to use Alpine"

**Comment by eta-ableton** [comment]
@rco-ableton This was all new to me yesterday so don't take my word as 100% accurate, but from what I understand, `apk` is Alpine's version of `apt`. And odd reason, the `supervisor` file moves when changing to Alpine, so without the last change, nothing works. 

Maybe @mst-ableton can shed more light on that, but I'm happy to add more detail to the commit message. Not sure if it should be split into two commits though?

**Comment by rco-ableton** [comment]
@eta-ableton at least some more detail in the commit would be fine for me.

**Comment by ala-ableton** [comment]
@eta-ableton it cannot be split into two commits. The Alpine version of `supervisord` needs the config file in the right place for `jenkins_exporter` to work.

**Comment by eta-ableton** [comment]
I've added a bit to the commit. @mst-ableton can you please confirm that what I've written is correct?

**Comment by nre-ableton** [comment]
Still LGTM. Thanks for adding some more detail in the commit message.

**Comment by rco-ableton** [comment]
> Therefore need to modify its path in order for the Dockerfile to run.

There seems to be a word missing here somewhere?

**Comment by eta-ableton** [comment]
@rco-ableton oops, thanks! Fixed

**Comment by mst-ableton** [comment]
@rco-ableton as @eta-ableton mentioned, Alpine uses `apk` instead of `apt` as its package management system (which is slightly confusing, as `.apks` is the extension for Android applications which are completely unrelated).

As for the `supervisord.conf` location: Debian (on which `python3-slim` is based) [has a line](https://stackoverflow.com/a/12226293) in its `/etc/supervisor/supervisord.conf` which loads additional configurations from `/etc/supervisor/conf.d/*.conf`, making the natural location to install a config `/etc/supervisor/conf.d/supervisord.conf`. Alpine does not have this configuration, which means `supervisord` only looks for a configuration file in the [default configuration paths](http://supervisord.org/configuration.html).

This means that in https://github.com/AbletonDevTools/rebaser/commit/31e09850c376962341687f6363856f7f5d1f406b we got "lucky": line 29 of `rebaser`'s [`Dockerfile`](https://github.com/AbletonDevTools/rebaser/blob/master/Dockerfile#L29) is broken -- that path won't work on Alpine. However, in [line 9](https://github.com/AbletonDevTools/rebaser/blob/master/Dockerfile#L9) we copy the entire contents of `.` into the Docker image's working directory -- including `supervisord.conf`. Since the first path `supervisord` checks is `$CWD/supervisord.conf`, it loads that and will not continue searching for other files.

As we're more selective to what we add in `jenkins_exporter`, we need to install it to the correct `supervisord.conf` path for Alpine.

**Comment by rco-ableton** [comment]
> As for the `supervisord.conf` location: Debian (on which `python3-slim` is based) [has a line](https://stackoverflow.com/a/12226293) in its `/etc/supervisor/supervisord.conf` which loads additional configurations from `/etc/supervisor/conf.d/*.conf`, making the natural location to install a config `/etc/supervisor/conf.d/supervisord.conf`. Alpine does not have this configuration, which means `supervisord` only looks for a configuration file in the [default configuration paths](http://supervisord.org/configuration.html).
>
> This means that in https://github.com/AbletonDevTools/rebaser/commit/31e09850c376962341687f6363856f7f5d1f406b we got "lucky": line 29 of `rebaser`'s [`Dockerfile`](https://github.com/AbletonDevTools/rebaser/blob/master/Dockerfile#L29) is broken -- that path won't work on Alpine. However, in [line 9](https://github.com/AbletonDevTools/rebaser/blob/master/Dockerfile#L9) we copy the entire contents of `.` into the Docker image's working directory -- including `supervisord.conf`. Since the first path `supervisord` checks is `$CWD/supervisord.conf`, it loads that and will not continue searching for other files.

Truly it's the year of Linux on a container infrastructure.

**Comment by eta-ableton** [comment]
@ablbot autosquash

**Pull request merged**
