### PR TITLE
Fix supervisord version

### PR DESCRIPTION
**Pull request by eta-ableton**
ptal @AbletonDevTools/gotham-city, thanks!

### CODE REVIEW

**Comment by eta-ableton** [comment]
@rco-ableton added!

**Comment by rco-ableton** [comment]
@eta-ableton er, I'm none the wiser about what the new version of `supervisor` does 😄

**Comment by eta-ableton** [comment]
@rco-ableton this one works and the old one doesn't? 😅

**Comment by eta-ableton** [comment]
@rco-ableton I'm actually not sure what other details I could add 😄

**Comment by mst-ableton** [comment]
@eta-ableton how about "The previous commit set the version to what was mistakenly assumed was the latest version available to Alpine. Since it wasn't, it caused errors on Docker image build. This PR corrects the Dockerfile to use the proper latest version."

**Comment by ala-ableton** [comment]
@eta-ableton you could add
```
Otherwise `docker build` fails with the following error message:

  ERROR: unsatisfiable constraints:
    supervisor-3.3.4-r1:
      breaks: world[supervisor=3.1.4-r0]
  The command '/bin/sh -c apk add --no-cache supervisor=3.1.4-r0' returned a non-zero code: 1
```

**Comment by rco-ableton** [comment]
Just a comment that version `3.1.4-r0` is not available to `apk` would be fine!

**Comment by eta-ableton** [comment]
Thank you for the suggestions! Just pushed with the added commit message.

**Pull request merged**
